# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kosuke Shimofuji's HomePage
email: kosuke.shimofuji@gmail.com
description: > # this means to ignore newlines until "baseurl:"
   私はコンピュータ技術により社会が発展するのが好きです。
   一方でコンピュータ技術による個人、企業、国家の犯罪について危惧しています。
   コンピュータ技術の進化の果てが、ディストピアなのかユートピアなのかを知りたいと思います。
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://KosukeShimofuji.GITHUB.IO" # the base hostname & protocol for your site
twitter_username: KosukeShimofuji
github_username:  KosukeShimofuji

# Build settings
markdown: kramdown
