# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kosuke Shimofuji's Home Page
email: kosuke.shimofuji@gmail.com
copyright: "&copy; 2016 Kosuke Shimofuji. All rights reaerved." 
description: > # this means to ignore newlines until "baseurl:"
    Information Security, Security Research.
permalink: /:year/:month/:day/:title/
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kosukeshimofuji.jp" # the base hostname & protocol for your site
twitter_username: KosukeShimofuji
github_username:  KosukeShimofuji

# Build settings
markdown: kramdown

# add gems 
gems:
      - jekyll-toc

